language: java
jdk:
- oraclejdk8
script:
- mvn clean package
after_success: 
  if [ "$TRAVIS_BRANCH" == "master" ] && [ "$TRAVIS_PULL_REQUEST" == "false" ]; then 
    travis_wait 20 mvn -Ppublish scm-publish:publish-scm
  fi
