language: java
jdk:
- oraclejdk8
script:
- mvn clean package
after_success:
  if [ "$TRAVIS_BRANCH" == "master" ] && [ "$TRAVIS_PULL_REQUEST" == "false" ]; then
    travis_wait 20 mvn package -Ppublish -DskipTests;
  fi    
env:
  global:
    secure: C+2j5U1VL/InECAU0YeTz3KOS4px0xmmOgmsSd+DcQp/4CzjFD/ll8QJrf6bebMAkPUe3ItBYEdHbBDvs51fpInmuWEo/quffV4Ug5yuQOyeGVCmqVh7lvAfCXWvQXW6Mjb3FhtN79MyYZQWdmS4/rKf5pgIEma6lLeU53LkG8qNW45uAuiPkRG5ZDnokeRMhatwQgX8UJixGV5c58qW7kO1wYL5LmzlQv76z/iVJaoo6aDoR9/U+qfMbx+Df6T21uJwyi1DYfdGaZmW7hDt8cEaJoGVRilEncf5HHDWzyWwyInuEf1bbpAOD7s6heynMhhlQOSOO2TnB1iGfgk/cBI5JyqFHvfXxN9jRrsPOGD2D+BviAteTIj6dxiHeNRMcxlcCUCmejqwd3QZvIKZdkix5dtFK5JaHtdJ6rntna88sxOt9nitALnomIX3n2JyZcgB/w7xLNhlrzEHQVxHL6FlfwerQu36Sy6sX0G7BL9bm4QFZ02laqlqJdLsGJmMQBgteHMqWm8VRf5HQ5bUi9r2jaz78trN+GPLTMfpNXAk4w6oL1gs7CtWCd012jWHfWGnT52E3gzZhkPJi21hfQj59dll8P7cPhB7FyqBnHU0L7evws/i98s71wGdjPy8E81lLrWhBlNVpunUrqIPCK91kn2tYV+wvB8wnh0qbIU=
