language: java
jdk:
- oraclejdk8
script:
- mvn clean package
after_success: 
  if [ "$TRAVIS_BRANCH" == "master" ] && [ "$TRAVIS_PULL_REQUEST" == "false" ]; then 
    travis_wait 60 mvn package -Ppublish -DskipTests;
  fi
