== Feature Recipes

=== Creating Fields

[source,groovy]
.Create a Field with a name and a type
----
include::{sourcedir}/geoscript/cookbook/FeatureRecipes.groovy[tags=createField,indent=0]
----
....
include::output/feature_field_create.txt[]
....

[source,groovy]
.Create a Geometry Field with a name and a geometry type and an optional projection
----
include::{sourcedir}/geoscript/cookbook/FeatureRecipes.groovy[tags=createGeometryField,indent=0]
----
....
include::output/feature_field_create_geometry.txt[]
....

[source,groovy]
.Create a Field with a List of Strings (name, type, projection)
----
include::{sourcedir}/geoscript/cookbook/FeatureRecipes.groovy[tags=createFieldFromList,indent=0]
----
....
include::output/feature_field_create_list.txt[]
....

[source,groovy]
.Create a Field from a Map where keys are name, type, proj
----
include::{sourcedir}/geoscript/cookbook/FeatureRecipes.groovy[tags=createFieldFromMap,indent=0]
----
....
include::output/feature_field_create_map.txt[]
....

[source,groovy]
.Access a Field's properties
----
include::{sourcedir}/geoscript/cookbook/FeatureRecipes.groovy[tags=getFieldProperties,indent=0]
----
....
include::output/feature_field_properties.txt[]
....

=== Creating Schemas

[source,groovy]
.Create a Schema from a list of Fields
----
include::{sourcedir}/geoscript/cookbook/FeatureRecipes.groovy[tags=createSchemaFromFields,indent=0]
----
....
include::output/schema_create_fields.txt[]
....

[source,groovy]
.Create a Schema from a list of Lists
----
include::{sourcedir}/geoscript/cookbook/FeatureRecipes.groovy[tags=createSchemaFromLists,indent=0]
----
....
include::output/schema_create_lists.txt[]
....

[source,groovy]
.Create a Schema from a list of Maps
----
include::{sourcedir}/geoscript/cookbook/FeatureRecipes.groovy[tags=createSchemaFromMaps,indent=0]
----
....
include::output/schema_create_maps.txt[]
....

[source,groovy]
.Create a Schema from a string
----
include::{sourcedir}/geoscript/cookbook/FeatureRecipes.groovy[tags=createSchemaFromString,indent=0]
----
....
include::output/schema_create_string.txt[]
....

=== Getting Schema Properties

[source,groovy]
.Get the Schema's name
----
include::{sourcedir}/geoscript/cookbook/FeatureRecipes.groovy[tags=getSchemaProperties_name,indent=0]
----
....
include::output/schema_properties_name.txt[]
....

[source,groovy]
.Get the Schema's geometry Field
----
include::{sourcedir}/geoscript/cookbook/FeatureRecipes.groovy[tags=getSchemaProperties_geom,indent=0]
----
....
include::output/schema_properties_geom.txt[]
....

[source,groovy]
.Get the Schema's Projection
----
include::{sourcedir}/geoscript/cookbook/FeatureRecipes.groovy[tags=getSchemaProperties_proj,indent=0]
----
....
include::output/schema_properties_proj.txt[]
....

[source,groovy]
.Get the Schema's URI
----
include::{sourcedir}/geoscript/cookbook/FeatureRecipes.groovy[tags=getSchemaProperties_uri,indent=0]
----
....
include::output/schema_properties_uri.txt[]
....

[source,groovy]
.Get the Schema's specification string
----
include::{sourcedir}/geoscript/cookbook/FeatureRecipes.groovy[tags=getSchemaProperties_spec,indent=0]
----
....
include::output/schema_properties_spec.txt[]
....

=== Getting Schema Fields

[source,groovy]
.Get the Schema's Fields
----
include::{sourcedir}/geoscript/cookbook/FeatureRecipes.groovy[tags=getSchemaFields_fields,indent=0]
----
....
include::output/schema_fields_fields.txt[]
....

[source,groovy]
.Get a Field
----
include::{sourcedir}/geoscript/cookbook/FeatureRecipes.groovy[tags=getSchemaFields_field_name,indent=0]
----
....
include::output/schema_fields_field.txt[]
....

[source,groovy]
.Get a Field
----
include::{sourcedir}/geoscript/cookbook/FeatureRecipes.groovy[tags=getSchemaFields_get,indent=0]
----
....
include::output/schema_fields_get.txt[]
....

[source,groovy]
.Check if a Schema has a Field
----
include::{sourcedir}/geoscript/cookbook/FeatureRecipes.groovy[tags=getSchemaFields_has,indent=0]
----
....
include::output/schema_fields_has.txt[]
....

=== Modifying Schemas

[source,groovy]
.Change the projection of a Schema
----
include::{sourcedir}/geoscript/cookbook/FeatureRecipes.groovy[tags=reprojectSchema,indent=0]
----
....
include::output/schema_reproject.txt[]
....

[source,groovy]
.Change the geometry type of a Schema
----
include::{sourcedir}/geoscript/cookbook/FeatureRecipes.groovy[tags=changeGeometryTypeSchema,indent=0]
----
....
include::output/schema_changegeometrytype.txt[]
....

[source,groovy]
.Change a Field definition of a Schema
----
include::{sourcedir}/geoscript/cookbook/FeatureRecipes.groovy[tags=changeFieldSchema,indent=0]
----
....
include::output/schema_changefield.txt[]
....

[source,groovy]
.Change Field definitions of a Schema
----
include::{sourcedir}/geoscript/cookbook/FeatureRecipes.groovy[tags=changeFieldsSchema,indent=0]
----
....
include::output/schema_changefields.txt[]
....

=== Creating Features from a Schema

[source,groovy]
.Create a Feature from a Schema with a Map of values
----
include::{sourcedir}/geoscript/cookbook/FeatureRecipes.groovy[tags=createFeatureFromSchemaMap,indent=0]
----
....
include::output/schema_create_feature_map.txt[]
....

[source,groovy]
.Create a Feature from a Schema with a List of values.  The order of the values must match the order of the Fields.
----
include::{sourcedir}/geoscript/cookbook/FeatureRecipes.groovy[tags=createFeatureFromSchemaList,indent=0]
----
....
include::output/schema_create_feature_list.txt[]
....

[source,groovy]
.Create a Feature from a Schema with another Feature.
----
include::{sourcedir}/geoscript/cookbook/FeatureRecipes.groovy[tags=createFeatureFromSchemaFeature,indent=0]
----
....
include::output/schema_create_feature_feature.txt[]
....

[source,groovy]
.Create an empty Feature from a Schema.
----
include::{sourcedir}/geoscript/cookbook/FeatureRecipes.groovy[tags=createFeatureFromSchemaEmpty,indent=0]
----
....
include::output/schema_create_feature_empty.txt[]
....