ifndef::imagesdir[:imagesdir: images]
ifndef::sourcedir[:sourcedir: ../../main/groovy]

== Layer Recipes

The Layer classes are in the *http://geoscript.github.io/geoscript-groovy/api/1.9.0/geoscript/layer/package-summary.html[geoscript.layer]* package.

A Layer is a collection of Features.

=== Getting a Layer's Properties

[source,groovy]
.Get a Layer from a Workspace and it's name
----
include::{sourcedir}/geoscript/cookbook/LayerRecipes.groovy[tags=getLayerProperties_name,indent=0]
----
....
include::output/layer_properties_name.txt[]
....

[source,groovy]
.The Layer's Format
----
include::{sourcedir}/geoscript/cookbook/LayerRecipes.groovy[tags=getLayerProperties_format,indent=0]
----
....
include::output/layer_properties_format.txt[]
....

[source,groovy]
.Count the number of Features
----
include::{sourcedir}/geoscript/cookbook/LayerRecipes.groovy[tags=getLayerProperties_count,indent=0]
----
....
include::output/layer_properties_count.txt[]
....

[source,groovy]
.Get the Layer's Projection
----
include::{sourcedir}/geoscript/cookbook/LayerRecipes.groovy[tags=getLayerProperties_proj,indent=0]
----
....
include::output/layer_properties_proj.txt[]
....

[source,groovy]
.Get the Bounds of the Layer
----
include::{sourcedir}/geoscript/cookbook/LayerRecipes.groovy[tags=getLayerProperties_bounds,indent=0]
----
....
include::output/layer_properties_bounds.txt[]
....

=== Getting a Layer's Features

[source,groovy]
.Iterate over a Layer's Features
----
include::{sourcedir}/geoscript/cookbook/LayerRecipes.groovy[tags=getLayerFeatures,indent=0]
----
....
include::output/layer_features.txt[]
....

[source,groovy]
.Iterate over a subset of a Layer's Features
----
include::{sourcedir}/geoscript/cookbook/LayerRecipes.groovy[tags=getLayerFeaturesFiltered,indent=0]
----
....
include::output/layer_features_filtered.txt[]
....

[source,groovy]
.Iterate over a Layer's Features with parameters.

----
include::{sourcedir}/geoscript/cookbook/LayerRecipes.groovy[tags=getLayerFeaturesWithParameters,indent=0]
----
....
include::output/layer_features_params.txt[]
....

Parameters

* filter: The Filter or Filter String to limit the Features. Defaults to null.
* sort:  A List of Lists that define the sort order [[Field or Field name, "ASC" or "DESC"],...]. Not all Layers support sorting!
* max:  The maximum number of Features to include
* start: The index of the record to start the cursor at.  Together with maxFeatures this simulates paging. Not all Layers support the start index and paging!
* fields: A List of Fields or Field names to include.  Used to select only a subset of Fields.

[source,groovy]
.Read all Feature into a List
----
include::{sourcedir}/geoscript/cookbook/LayerRecipes.groovy[tags=getLayerFeaturesInAList,indent=0]
----
....
include::output/layer_list_features.txt[]
....

=== Reading and Writing Features

The Layer IO classes are in the *http://geoscript.github.io/geoscript-groovy/api/1.9.0/geoscript/layer/io/package-summary.html[geoscript.layer.io]* package.

==== Finding Layer Writer and Readers

[source,groovy]
.List all Layer Writers
----
include::{sourcedir}/geoscript/cookbook/LayerRecipes.groovy[tags=listLayerWriters,indent=0]
----
....
include::output/layer_list_writers.txt[]
....

[source,groovy]
.Find a Layer Writer
----
include::{sourcedir}/geoscript/cookbook/LayerRecipes.groovy[tags=findLayerWriter,indent=0]
----
....
include::output/layer_find_writer.txt[]
....

[source,groovy]
.List all Layer Readers
----
include::{sourcedir}/geoscript/cookbook/LayerRecipes.groovy[tags=listLayerReaders,indent=0]
----
....
include::output/layer_list_readers.txt[]
....

[source,groovy]
.Find a Layer Reader
----
include::{sourcedir}/geoscript/cookbook/LayerRecipes.groovy[tags=findLayerReader,indent=0]
----
....
include::output/layer_find_reader.txt[]
....

==== GeoJSON

[source,groovy]
.Get GeoJSON String from a Layer
----
include::{sourcedir}/geoscript/cookbook/LayerRecipes.groovy[tags=layerToGeoJSONString,indent=0]
----
....
include::output/layer_to_geojson_string.txt[]
....

==== GeoBuf

[source,groovy]
.Get GeoBuf String from a Layer
----
include::{sourcedir}/geoscript/cookbook/LayerRecipes.groovy[tags=layerToGeobufString,indent=0]
----
....
include::output/layer_to_geobuf_string.txt[]
....

==== GML

[source,groovy]
.Get GML String from a Layer
----
include::{sourcedir}/geoscript/cookbook/LayerRecipes.groovy[tags=layerToGMLString,indent=0]
----
....
include::output/layer_to_gml_string.txt[]
....

==== KML

[source,groovy]
.Get KML String from a Layer
----
include::{sourcedir}/geoscript/cookbook/LayerRecipes.groovy[tags=layerToKMLString,indent=0]
----
....
include::output/layer_to_kml_string.txt[]
....


