ifndef::imagesdir[:imagesdir: images]
ifndef::sourcedir[:sourcedir: ../../main/groovy]

== Layer Recipes

The Layer classes are in the *http://geoscript.github.io/geoscript-groovy/api/1.9.0/geoscript/layer/package-summary.html[geoscript.layer]* package.

A Layer is a collection of Features.

=== Getting a Layer's Properties

[source,groovy]
.Get a Layer from a Workspace and it's name
----
include::{sourcedir}/geoscript/cookbook/LayerRecipes.groovy[tags=getLayerProperties_name,indent=0]
----
....
include::output/layer_properties_name.txt[]
....

[source,groovy]
.The Layer's Format
----
include::{sourcedir}/geoscript/cookbook/LayerRecipes.groovy[tags=getLayerProperties_format,indent=0]
----
....
include::output/layer_properties_format.txt[]
....

[source,groovy]
.Count the number of Features
----
include::{sourcedir}/geoscript/cookbook/LayerRecipes.groovy[tags=getLayerProperties_count,indent=0]
----
....
include::output/layer_properties_count.txt[]
....

[source,groovy]
.Get the Layer's Projection
----
include::{sourcedir}/geoscript/cookbook/LayerRecipes.groovy[tags=getLayerProperties_proj,indent=0]
----
....
include::output/layer_properties_proj.txt[]
....

[source,groovy]
.Get the Bounds of the Layer
----
include::{sourcedir}/geoscript/cookbook/LayerRecipes.groovy[tags=getLayerProperties_bounds,indent=0]
----
....
include::output/layer_properties_bounds.txt[]
....

=== Getting a Layer's Features

[source,groovy]
.Iterate over a Layer's Features
----
include::{sourcedir}/geoscript/cookbook/LayerRecipes.groovy[tags=getLayerFeatures,indent=0]
----
....
include::output/layer_features.txt[]
....

[source,groovy]
.Iterate over a subset of a Layer's Features
----
include::{sourcedir}/geoscript/cookbook/LayerRecipes.groovy[tags=getLayerFeaturesFiltered,indent=0]
----
....
include::output/layer_features_filtered.txt[]
....

[source,groovy]
.Iterate over a Layer's Features with parameters.

----
include::{sourcedir}/geoscript/cookbook/LayerRecipes.groovy[tags=getLayerFeaturesWithParameters,indent=0]
----
....
include::output/layer_features_params.txt[]
....

Parameters

* filter: The Filter or Filter String to limit the Features. Defaults to null.
* sort:  A List of Lists that define the sort order [[Field or Field name, "ASC" or "DESC"],...]. Not all Layers support sorting!
* max:  The maximum number of Features to include
* start: The index of the record to start the cursor at.  Together with maxFeatures this simulates paging. Not all Layers support the start index and paging!
* fields: A List of Fields or Field names to include.  Used to select only a subset of Fields.
