ifndef::imagesdir[:imagesdir: images]
ifndef::sourcedir[:sourcedir: ../../main/groovy]

== Spatial Index Recipes

The Index classes are in the *http://geoscript.github.io/geoscript-groovy/api/1.13.0/geoscript/index/package-summary.html[geoscript.index]* package.

=== Using STRtree

[source,groovy]
.Create a STRtree spatial index
----
include::{sourcedir}/geoscript/cookbook/SpatialIndexRecipes.groovy[tags=createSTRtree_create,indent=0]
----

[source,groovy]
.Insert Geometries and their Bounds
----
include::{sourcedir}/geoscript/cookbook/SpatialIndexRecipes.groovy[tags=createSTRtree_insert,indent=0]
----

[source,groovy]
.Get the size of the index
----
include::{sourcedir}/geoscript/cookbook/SpatialIndexRecipes.groovy[tags=createSTRtree_size,indent=0]
----
....
include::output/spatialindex_strtree_size.txt[]
....

[source,groovy]
.Query the index
----
include::{sourcedir}/geoscript/cookbook/SpatialIndexRecipes.groovy[tags=createSTRtree_results,indent=0]
----
....
include::output/spatialindex_strtree_results.txt[]
....

=== Using Quadtree

[source,groovy]
.Create a Quadtree spatial index
----
include::{sourcedir}/geoscript/cookbook/SpatialIndexRecipes.groovy[tags=createQuadtree_create,indent=0]
----

[source,groovy]
.Insert Geometries and their Bounds
----
include::{sourcedir}/geoscript/cookbook/SpatialIndexRecipes.groovy[tags=createQuadtree_insert,indent=0]
----

[source,groovy]
.Get the size of the index
----
include::{sourcedir}/geoscript/cookbook/SpatialIndexRecipes.groovy[tags=createQuadtree_size,indent=0]
----
....
include::output/spatialindex_quadtree_size.txt[]
....

[source,groovy]
.Query the index with a Bounds
----
include::{sourcedir}/geoscript/cookbook/SpatialIndexRecipes.groovy[tags=createQuadtree_results,indent=0]
----
....
include::output/spatialindex_quadtree_results.txt[]
....

[source,groovy]
.Query the entire index
----
include::{sourcedir}/geoscript/cookbook/SpatialIndexRecipes.groovy[tags=createQuadtree_allresults,indent=0]
----
....
include::output/createQuadtree_allresults.txt[]
....

[source,groovy]
.Remove an item from the index
----
include::{sourcedir}/geoscript/cookbook/SpatialIndexRecipes.groovy[tags=createQuadtree_remove,indent=0]
----
....
include::output/spatialindex_quadtree_remove.txt[]
....

=== Using GeoHash

[source,groovy]
.Encode a Point as a String
----
include::{sourcedir}/geoscript/cookbook/SpatialIndexRecipes.groovy[tags=geohashEncodePoint,indent=0]
----
....
include::output/spatialindex_geohash_encodepoints.txt[]
....

[source,groovy]
.Decode a Point from a String
----
include::{sourcedir}/geoscript/cookbook/SpatialIndexRecipes.groovy[tags=geohashDecodeString,indent=0]
----
....
include::output/spatialindex_geohash_decodestring.txt[]
....

[source,groovy]
.Encode a Point as a Long
----
include::{sourcedir}/geoscript/cookbook/SpatialIndexRecipes.groovy[tags=geohashEncodePointAsLong,indent=0]
----
....
include::output/spatialindex_geohash_encodepoints_long.txt[]
....

[source,groovy]
.Decode a Point from a Long
----
include::{sourcedir}/geoscript/cookbook/SpatialIndexRecipes.groovy[tags=geohashDecodeLong,indent=0]
----
....
include::output/spatialindex_geohash_decodelong.txt[]
....

[source,groovy]
.Decode a Bounds from a String
----
include::{sourcedir}/geoscript/cookbook/SpatialIndexRecipes.groovy[tags=geohashDecodeBoundsFromString,indent=0]
----
....
include::output/spatialindex_geohash_decode_bounds_string.txt[]
....

[source,groovy]
.Decode a Bounds from a Long
----
include::{sourcedir}/geoscript/cookbook/SpatialIndexRecipes.groovy[tags=geohashDecodeBoundsFromLong,indent=0]
----
....
include::output/spatialindex_geohash_decode_bounds_string.txt[]
....

[source,groovy]
.Find neighboring geohash strings
----
include::{sourcedir}/geoscript/cookbook/SpatialIndexRecipes.groovy[tags=geohashNeighborFromString,indent=0]
----
....
include::output/spatialindex_geohash_neighbor_from_string.txt[]
....

[source,groovy]
.Find neighboring geohash longs
----
include::{sourcedir}/geoscript/cookbook/SpatialIndexRecipes.groovy[tags=geohashNeighborFromLong,indent=0]
----
....
include::output/spatialindex_geohash_neighbor_from_long.txt[]
....

[source,groovy]
.Find all neighboring geohash strings
----
include::{sourcedir}/geoscript/cookbook/SpatialIndexRecipes.groovy[tags=geohashNeighborsFromString,indent=0]
----
....
include::output/spatialindex_geohash_neighbors_from_string.txt[]
....

[source,groovy]
.Find all neighboring geohash longs
----
include::{sourcedir}/geoscript/cookbook/SpatialIndexRecipes.groovy[tags=geohashNeighborsFromLong,indent=0]
----
....
include::output/spatialindex_geohash_neighbors_from_long.txt[]
....

[source,groovy]
.Find all geohashes as strings within a Bounds
----
include::{sourcedir}/geoscript/cookbook/SpatialIndexRecipes.groovy[tags=geohashBboxesAsStrings,indent=0]
----
....
include::output/spatialindex_geohash_bboxes_as_strings.txt[]
....

[source,groovy]
.Find all geohashes as longs within a Bounds
----
include::{sourcedir}/geoscript/cookbook/SpatialIndexRecipes.groovy[tags=geohashBboxesAsLongs,indent=0]
----
....
include::output/spatialindex_geohash_bboxes_as_longs.txt[]
....