ifndef::imagesdir[:imagesdir: images]
ifndef::sourcedir[:sourcedir: ../../main/groovy]

== Workspace Recipes

The Workspace classes are in the *http://geoscript.github.io/geoscript-groovy/api/1.9.0/geoscript/workspace/package-summary.html[geoscript.workspace]* package.

A Workspace is a collection of Layers.  You can create, add, remove, and get Layers.  There are many
different kinds of Workspaces in GeoScript including Memory, PostGIS, Directory (for Shapefiles), GeoPackage,
and many more.

=== Using Workspaces

[source,groovy]
.Create a Workspace
----
include::{sourcedir}/geoscript/cookbook/WorkspaceRecipes.groovy[tags=createWorkspace,indent=0]
----

[source,groovy]
.Create a Layer
----
include::{sourcedir}/geoscript/cookbook/WorkspaceRecipes.groovy[tags=createLayer,indent=0]
----
....
include::output/workspace_create_layer.txt[]
....

[source,groovy]
.Check whether a Workspace has a Layer by name
----
include::{sourcedir}/geoscript/cookbook/WorkspaceRecipes.groovy[tags=hasLayer,indent=0]
----
....
include::output/workspace_has_layer.txt[]
....

[source,groovy]
.Get a Layer from a Workspace
----
include::{sourcedir}/geoscript/cookbook/WorkspaceRecipes.groovy[tags=getLayer,indent=0]
----
....
include::output/workspace_get_layer.txt[]
....

[source,groovy]
.Add a Layer to a Workspace
----
include::{sourcedir}/geoscript/cookbook/WorkspaceRecipes.groovy[tags=addLayer,indent=0]
----
....
include::output/workspace_add_layer.txt[]
....

[source,groovy]
.Get the names of all Layers in a Workspace
----
include::{sourcedir}/geoscript/cookbook/WorkspaceRecipes.groovy[tags=getNames,indent=0]
----
....
include::output/workspace_get_names.txt[]
....

[source,groovy]
.Remove a Layer from a Workspace
----
include::{sourcedir}/geoscript/cookbook/WorkspaceRecipes.groovy[tags=removeLayer,indent=0]
----
....
include::output/workspace_remove_layer.txt[]
....

[source,groovy]
.Close the Workspace when you are done
----
include::{sourcedir}/geoscript/cookbook/WorkspaceRecipes.groovy[tags=closeWorkspace,indent=0]
----

=== Using a Directory Workspace

A Directory Workspace is a directory of Shapefiles.

[source,groovy]
.Create a Directory Workspace
----
include::{sourcedir}/geoscript/cookbook/WorkspaceRecipes.groovy[tags=createDirectoryWorkspace_1,indent=0]
----
....
include::output/workspace_directory_1.txt[]
....

[source,groovy]
.View the Workspace's format
----
include::{sourcedir}/geoscript/cookbook/WorkspaceRecipes.groovy[tags=createDirectoryWorkspace_2,indent=0]
----
....
include::output/workspace_directory_2.txt[]
....

[source,groovy]
.View the Workspace's File
----
include::{sourcedir}/geoscript/cookbook/WorkspaceRecipes.groovy[tags=createDirectoryWorkspace_3,indent=0]
----
....
include::output/workspace_directory_3.txt[]
....

[source,groovy]
.View the Workspace's list of Layer names
----
include::{sourcedir}/geoscript/cookbook/WorkspaceRecipes.groovy[tags=createDirectoryWorkspace_4,indent=0]
----
....
include::output/workspace_directory_4.txt[]
....

[source,groovy]
.Get a Layer by name
----
include::{sourcedir}/geoscript/cookbook/WorkspaceRecipes.groovy[tags=createDirectoryWorkspace_5,indent=0]
----
....
include::output/workspace_directory_5.txt[]
....

[source,groovy]
.Close the Directory when done.
----
include::{sourcedir}/geoscript/cookbook/WorkspaceRecipes.groovy[tags=createDirectoryWorkspace_6,indent=0]
----

=== Investigating Workspaces

[source,groovy]
.Get available Workspace names
----
include::{sourcedir}/geoscript/cookbook/WorkspaceRecipes.groovy[tags=getWorkspaceNames,indent=0]
----
....
include::output/workspace_get_names.txt[]
....

[source,groovy]
.Get parameters for a Workspace
----
include::{sourcedir}/geoscript/cookbook/WorkspaceRecipes.groovy[tags=getWorkspaceParameters,indent=0]
----
....
include::output/workspace_get_parameters.txt[]
....

=== Creating Workspaces

==== Creating a Workspace from a connection string

You can create a Workspace from a connection string that contains paramters in key=value format with optional single quotes.

[source,groovy]
.Create a Shapefile Workspace
----
include::{sourcedir}/geoscript/cookbook/WorkspaceRecipes.groovy[tags=getWorkspaceFromString_Shapefile,indent=0]
----

[source,groovy]
.Create a GeoPackage Workspace
----
include::{sourcedir}/geoscript/cookbook/WorkspaceRecipes.groovy[tags=getWorkspaceFromString_GeoPackage,indent=0]
----

[source,groovy]
.Create a Spatialite Workspace
----
include::{sourcedir}/geoscript/cookbook/WorkspaceRecipes.groovy[tags=getWorkspaceFromString_Spatialite,indent=0]
----

==== Creating a Workspace from a connection map

You can create a Workspace from a connection map that contains paramters.

[source,groovy]
.Create a H2 Workspace
----
include::{sourcedir}/geoscript/cookbook/WorkspaceRecipes.groovy[tags=getWorkspaceFromMap_H2,indent=0]
----

[source,groovy]
.Create a PostGIS Workspace
----
include::{sourcedir}/geoscript/cookbook/WorkspaceRecipes.groovy[tags=getWorkspaceFromMap_PostGIS,indent=0]
----

[source,groovy]
.Create a GeoBuf Workspace
----
include::{sourcedir}/geoscript/cookbook/WorkspaceRecipes.groovy[tags=getWorkspaceFromMap_Geobuf,indent=0]
----

==== Creating Directory Workspaces

[source,groovy]
.Create a Directory Workspace from a directory name
----
include::{sourcedir}/geoscript/cookbook/WorkspaceRecipes.groovy[tags=createDirectoryWorkspaceFromName,indent=0]
----

....
include::output/workspace_directory_name.txt[]
....

[source,groovy]
.Create a Directory Workspace from a File directory
----
include::{sourcedir}/geoscript/cookbook/WorkspaceRecipes.groovy[tags=createDirectoryWorkspaceFromFile,indent=0]
----

....
include::output/workspace_directory_file.txt[]
....

[source,groovy]
.Create a Directory Workspace from a URL
----
include::{sourcedir}/geoscript/cookbook/WorkspaceRecipes.groovy[tags=createDirectoryWorkspaceFromUrl,indent=0]
----

....
include::output/workspace_directory_url.txt[]
....

==== Creating GeoPackage Workspaces

[source,groovy]
.Create a GeoPackage Workspace from a file name
----
include::{sourcedir}/geoscript/cookbook/WorkspaceRecipes.groovy[tags=createGeoPackageWorkspaceFromName,indent=0]
----

....
include::output/workspace_geopackage_name.txt[]
....

[source,groovy]
.Create a GeoPackage Workspace from a File
----
include::{sourcedir}/geoscript/cookbook/WorkspaceRecipes.groovy[tags=createGeoPackageWorkspaceFromFile,indent=0]
----

....
include::output/workspace_geopackage_file.txt[]
....

==== Creating H2 Workspaces

[source,groovy]
.Create a H2 Workspace from a File
----
include::{sourcedir}/geoscript/cookbook/WorkspaceRecipes.groovy[tags=createH2WorkspaceFromFile,indent=0]
----

....
include::output/workspace_h2_file.txt[]
....

==== Creating Geobuf Workspaces

[source,groovy]
.Create a Geobuf Workspace from a File
----
include::{sourcedir}/geoscript/cookbook/WorkspaceRecipes.groovy[tags=createGeobufWorkspaceFromFile,indent=0]
----

....
include::output/workspace_geobuf_file.txt[]
....